### PR TITLE
added ms engine

### PR DESCRIPTION
**Pull request by furesoft**

### CODE REVIEW

**Comment by Taritsyn** [comment]
Hello, Chris!

That are these pieces of code from the ClearScript project? Why do we need a Windows Script Engine?

**Comment by furesoft** [comment]
because sometimes the clearscript v8 wrapper dont work correctly

**Comment by Taritsyn** [comment]
How does this relate to the JavaScriptEngineSwitcher.Msie?

**Comment by Daniel15** [comment]
It doesn't seem appropriate to copy and paste 10,000 lines of code from ClearScript...

**Comment by Taritsyn** [comment]
I'm closing this pull request, because it is not related to the MSIE JS Engine (Windows Script Engine is a totally different).

**Pull request closed without merging**
